### ISSUE TITLE
Ujednolicenia nazwy kontrolerów | Poprawa struktury projektu BackEnd

### ISSUE THREAD

**Issue by Kykaneek** [Kykaneek/RouteMail#10]
Ze względu na potrzebę stworzenia zleceń i wyrobieniem się z czasem przejmuje poprawę kontrolerów  <br>

@mkk90367 for your information(fyi)

**Comment by Kykaneek** [comment]
@mkk90367 prośba o weryfikacja poprawności działania po swojej stronie

**Comment by mkk90367** [comment]
Potwierdzam, że dokonane zmiany są prawidłowe.

**Comment by Kykaneek** [comment]
To prosze zamknąć zgłoszenie i wkleić link do niego do zadania na Jira https://github.com/Kykaneek/RouteMail/issues/10
