### ISSUE TITLE
KGDPMK-55 | Widok Adresów i Miejscowości (CRUD)

### ISSUE THREAD

**Issue by danielos54** [Kykaneek/RouteMail#13]
![miejscowości](https://github.com/Kykaneek/RouteMail/assets/114804469/899b6ee0-b00b-46c8-b5c5-cd60264b0f95)

1. Ekran wyświetlania miejscowości na tym ekranie administrator wybiera miejscowość albo dodaje nową do bazy,
2. Ekran szczegółów poszczególnych miejscowości tutaj administrator może wybrać adres do edycji wrócić do poprzedniego okna dodać nowy adres albo usunąć wybraną miejscowość,
3. Ekran szczegółów adresów w tym miejscu admin ma możliwość wybrania koordynatów do edycji wrócić do poprzedniego okna albo usunąć wybrany adres,
4. Ekran edycji albo dodawania w momencie edycji admin edytuje nazwę miejscowości i ilość istniejących w niej adresów, w kwestii samych adresów edytuje jedynie ich koordynaty, jeśli chodzi o dodawanie historia jest podobna.

**Comment by Kykaneek** [comment]
koordynaty pobierane są z arcgis automatycznie i wpisywane do bazy

**Comment by danielos54** [comment]
Kody wyświetlania Adresów i Miejscowości CRUD do zweryfikowania.
1.
[Widok_Miejscowości_CRUD_głowna.txt](https://github.com/Kykaneek/RouteMail/files/15201216/Widok_Miejscowosci_CRUD_glowna.txt)
2.
[Widok_Miejscowości_CRUD_szczegółyM.txt](https://github.com/Kykaneek/RouteMail/files/15201224/Widok_Miejscowosci_CRUD_szczegolyM.txt)
3.
[Widok_Miejscowości_CRUD_szczegółyA.txt](https://github.com/Kykaneek/RouteMail/files/15201226/Widok_Miejscowosci_CRUD_szczegolyA.txt)
4.
[Widok_Miejscowości_CRUD_edycjaM.txt](https://github.com/Kykaneek/RouteMail/files/15201228/Widok_Miejscowosci_CRUD_edycjaM.txt)
5.
[Widok_Miejscowości_CRUD_edycjaA.txt](https://github.com/Kykaneek/RouteMail/files/15201229/Widok_Miejscowosci_CRUD_edycjaA.txt)

**Comment by mkk90367** [comment]
Jaki jest format wprowadzania koordynat i jak są przechowywane w bazie danych ?

**Comment by mkk90367** [comment]
![image](https://github.com/Kykaneek/RouteMail/assets/119660944/dec18cc7-62a7-4edb-b8bc-659532e3e74a)
