### ISSUE TITLE
KGDPMK-56 | Widok Pojazdów CRUD

### ISSUE THREAD

**Issue by danielos54** [Kykaneek/RouteMail#14]
![Pojazdy](https://github.com/Kykaneek/RouteMail/assets/114804469/6ef12a25-601f-4927-ac63-46aad19d708d)

1. Ekran wyświetlania pojazdów na tym ekranie administrator wybiera pojazd albo dodaje nowy do bazy,
2. Ekran szczegółów pojazdu tutaj administrator ma możliwość edytować albo w ogóle usunąć pojazd, w ostateczności nie podejmować żadnej akcji i wrócić,
3. Ekran edycji albo dodawania pojazdu administrator może edytować wybrany element (Markę lub Model albo obydwa) następnie zatwierdzić zmiany lub z nich zrezygnować, taka sama historia tyczy się dodawania pojazdu.

**Comment by danielos54** [comment]
Kody wyświetlania pojazdów CRUD do zweryfikowania.
1. 
[Widok_Pojazdów_CRUD_główny.txt](https://github.com/Kykaneek/RouteMail/files/15198337/Widok_Pojazdow_CRUD_glowny.txt)
2.
[Widok_Pojazdów_CRUD_szczegóły.txt](https://github.com/Kykaneek/RouteMail/files/15198338/Widok_Pojazdow_CRUD_szczegoly.txt)
3.
[Widok_Pojazdów_CRUD_edytuj.txt](https://github.com/Kykaneek/RouteMail/files/15198339/Widok_Pojazdow_CRUD_edytuj.txt)

**Comment by Kykaneek** [comment]
Prośba o spięcie Backend i FrontEnd i Testy do Niedzieli

**Comment by danielos54** [comment]
Do dodanie jedynie odświeżanie podczas edycji ponieważ zaraz po akceptacji dane w oknie edycji pozostają nie zmienione.
