### ISSUE TITLE
KGDPMK-54 | Widok CRUD Użykownika

### ISSUE THREAD

**Issue by mkk90367** [Kykaneek/RouteMail#15]
![image](https://github.com/Kykaneek/RouteMail/assets/119660944/e33165af-fc3a-40c7-a908-49aece884e95)

1. Strona wyglądu i wyświetlania użytkowników
- pierwsza strona, zawierająca przyciski powrót i dodaj użytkownika
- widok scoll-view na którym będą wyświetlani użytkownicy
- w widoku podglądowym użytkownika znajdują się informacje podglądowe o użytkowniku wraz z przyciskiem sprawdzenia szczegółów
- w informacjach szczegółowych o użytkownikach znajdują się informacje takie jak:
  - numer kuriera, pojazd, zdjęcie, imię i nazwisko
- przycisk powrót do menu głównego

2. Szczegóły użytkownika
- na tym widoku wyświetlają się wszystkie informacje na temat użytkownika
   - imię nazwisko
   - zdjęcie
   - email
   - numer kuriera
   - pojazd
   - aktualne zlecenie
   - rola
- w widoku znajdują się także przyciski
  - przycisk zmień hasło/resetuj hasło - formularz do zmiany informacji o haśle
  - usuń użytkownika 
  - modyfikuj użytkownika - przycisk do przeniesienia do formularza modyfikacji użytkownika
  - przycisk powrót do strony z użytkownikami

**Comment by mkk90367** [comment]
![Widok_CRUD_Użykownika_1](https://github.com/Kykaneek/RouteMail/assets/119660944/152cf43d-169d-4d8b-8ee7-a1538c9b99de)
[Widok_CRUD_Użykownika_1.txt](https://github.com/Kykaneek/RouteMail/files/15197727/Widok_CRUD_Uzykownika_1.txt)
![Widok_CRUD_Użykownika_2](https://github.com/Kykaneek/RouteMail/assets/119660944/98d0eafe-4a9e-4aea-a56a-2beb705e69d1)
[Widok_CRUD_Użykownika_2.txt](https://github.com/Kykaneek/RouteMail/files/15197728/Widok_CRUD_Uzykownika_2.txt)
![Widok_CRUD_Użykownika_3](https://github.com/Kykaneek/RouteMail/assets/119660944/9cef7635-132e-4eea-ba3b-ea0c71d2c1b1)
[Widok_CRUD_Użykownika_3.txt](https://github.com/Kykaneek/RouteMail/files/15197729/Widok_CRUD_Uzykownika_3.txt)
![Widok_CRUD_Użykownika_4](https://github.com/Kykaneek/RouteMail/assets/119660944/98cdb25d-2720-4612-b60e-34514ac8ffd6)
[Widok_CRUD_Użykownika_4.txt](https://github.com/Kykaneek/RouteMail/files/15197730/Widok_CRUD_Uzykownika_4.txt)
![Widok_CRUD_Użykownika_5](https://github.com/Kykaneek/RouteMail/assets/119660944/f15d8d76-30af-4fc3-b605-e527801ebc8c)
[Widok_CRUD_Użykownika_5.txt](https://github.com/Kykaneek/RouteMail/files/15197731/Widok_CRUD_Uzykownika_5.txt)

**Comment by Kykaneek** [comment]
Poprawiono Widok Listy <br>
![image](https://github.com/Kykaneek/RouteMail/assets/116293496/7944a34b-816f-4898-90ec-a2afd40b95eb)

**Comment by mkk90367** [comment]
Poprawiony widok listy prezentuje się bardzo ładnie.
