### ISSUE TITLE
KGDPMK-50 | Rejestracja i Autoryzacja Użytkowników wraz z zasalaniem i Hashowaniem

### ISSUE THREAD

**Issue by Kykaneek** [Kykaneek/RouteMail#19]
1. Wprowadzenie użytkowników<br>
2. Hash + Salt <br>
3. Autoryzacja i sesja 
4. Widok user + admin

**Comment by mkk90367** [comment]
Wtrącę swoje trzy grosze. A mianowicie, aby bezpiecznie obsługiwać uwierzytelnianie użytkowników w aplikacji React Native z bazą danych MySQL, zazwyczaj hashujemy hasła przed zapisaniem ich w bazie danych. Możemy skorzystać z bezpiecznego algorytmu hashującego, takiego jak bcrypt, aby hashować hasła przed zapisaniem ich w bazie danych. Aby to osiągnąć, używamy biblioteki bcrypt w Node.js, którą można zainstalować poprzez wpisanie w cmd: npm install bcrypt. Następnie w kodzie backendowym w Node.js wpisujemy: const bcrypt = require('bcrypt'); ustawiamy również liczbę rund solenia: const saltRounds = 10; funkcja hashująca może wyglądać jak poniżej: `async function hashowaniePWS(moje_haslo) {
    return await bcrypt.hash(moje_haslo, saltRounds);
}`. Przykład użycia będzie wyglądał mniej więcej tak: `const hasloHaszowane = await hashowaniePWS('hasloUseraZbazy');` W daleszej części implementacji tworzymy formatki w aplikacji React Native do rejestracji i logowania użytkownika. Gdy użytkownik się zarejestruje, zaszyfrujemy hasło przed wysłaniem go do backendu w celu przechowywania. Przykładowy kod z procesem rejestracji w React Native znaleziony w sieci: `import axios from 'axios';
async function register(username, email, password) {
    try {
        const hashedPassword = await hashPassword(password);
        await axios.post('http://your-backend-url/register', {
            username,
            email,
            password: hashedPassword
        });
        // Handle success
    } catch (error) {
        // Handle error
    }
}
W toku dalszej implementacji weryfikujemy hasła podczas logowania: tzn. kiedy użytkownik próbuje się zalogować, pobieramy zaszyfrowane hasło z bazy danych na podstawie podanej nazwy użytkownika lub adresu e-mail, a następnie porównujemy je z zaszyfrowaną wersją hasła podaną przez użytkownika. Przykładowy proces logowania w React Native : import axios from 'axios';

async function login(email, password) {
    try {
        const response = await axios.post('http://your-backend-url/login', {
            email,
            password
        });
        // Handle successful login
    } catch (error) {
        // Handle login failure
    }
} W backendzie porównujemy zaszyfrowane hasło z hasłem przechowywanym w bazie danych za pomocą bcrypt.compare(): const bcrypt = require('bcrypt');

async function verifyPassword(plainPassword, hashedPassword) {
    return await bcrypt.compare(plainPassword, hashedPassword);
}

// Przykład użycia
const isPasswordCorrect = await verifyPassword('user_password', hashedPasswordFromDatabase); Wykonując te wszystkie załączone kroki, możemy bezpiecznie obsługiwać uwierzytelnianie użytkowników w aplikacji React Native przy użyciu bazy danych MySQL i szyfrowania haseł.

**Comment by mkk90367** [comment]
Oczywiście zamiast Axios'a możemy użyć w naszej aplikacji zwykłego, standardowego fetch'a.

**Comment by mkk90367** [comment]
Tutaj jest dobrze zobrazowane jak to zrobić : https://medium.com/@arunchaitanya/salting-and-hashing-passwords-with-bcrypt-js-a-comprehensive-guide-f5e31de3c40c
Potrzebuję jedynie dokładniejszego info/delikatnego nakierowania jeśli chodzi o integrację względem naszego programu.
