### ISSUE TITLE
KGDPMK-57 | Widok pojazdów

### ISSUE THREAD

**Issue by Kykaneek** [Kykaneek/RouteMail#20]
Stworzenie widoku wybrania pojazdu pracownika poczty.<br>
Jedna strona scrollview - wyświetla wszystkie pojazdy dla użytkowników <br>
![obraz](https://github.com/Kykaneek/RouteMail/assets/116293496/40b9ce4d-613c-419b-9224-a4d608717c92)
<br><br>
Strona z listą pojazdów do wyboru 

Blok pojazdu składa się z 3 bloków:
 - Dane pojazdu 
   - Zawiera informacje o marce i modelu 
 - Dane kuriera 
   - Wyświetla numer kuriera, imie i nazwisko
 - Przycisk zajmij pojazd / zwolnij pojazd
   1. Pojazd nie jest zajęty przez kuriera 
   2. Pojazd aktualny użytkownik nie zajął innego pojazdu(jeżeli jest pojazd zajęty przez użyttkownika nie może on wybrać innego dopuki go nie zwolni)
  - Jeśli pojazd jest wolny po wybraniu tego przycisku pojawia się alert z informacja "Czy na pewno chcesz przypisać pojazd do siebie?"(Tak/Nie)
  - Po wybraniu Tak przycisk zmienia się na zwolnij pojazd. Analogicznie też o wciśnięciu ma się pojawić alert z rezygnacji użytkowania pojazdu

**Comment by mkk90367** [comment]
Wstawiam plik z implementacją robioną zgodnie z powyższymi wymogami. Nie wszystko w niej ze sobą współgra i trzeba będzie to poprawić.
[KGDPMK-57 Widok pojazdów.txt](https://github.com/Kykaneek/RouteMail/files/15287143/KGDPMK-57.Widok.pojazdow.txt)

**Comment by mkk90367** [comment]
![image](https://github.com/Kykaneek/RouteMail/assets/119660944/ac030a33-911a-4300-b8b3-f107494945ad)
![image](https://github.com/Kykaneek/RouteMail/assets/119660944/abf8a687-e4e8-4999-b7cb-b373a1feea7c)
![image](https://github.com/Kykaneek/RouteMail/assets/119660944/4447c0e9-3571-4f89-9481-1dbf49a68123)

**Comment by mkk90367** [comment]
Zadanie wykonane - dodałem niezbędne poprawki do wyżej wstawionego kodu i teraz wszystko działa zgodnie z wytycznymi.
Alert "Czy na pewno chcesz zwolnić pojazd?" zostaje wyświetlony po naciśnięciu myszką przycisku "Zwolnij pojazd", natomiast
alert "Pojazd jest zajęty - Wybierz inny pojazd" zostaje wyświetlony po naciśnięciu myszką prostokątnego bloku pojazdu.
Vechicles zmieniłem na vehicles, bo to jest poprawne nazewnictwo. Zmiany zakomitowałem na git w gałęzi develop.

https://github.com/Kykaneek/RouteMail/commit/1f753efd39a8e7f308fab41ed9664ee6ad02c861

**Comment by mkk90367** [comment]
Lekkie podrasowanie UI.
![image](https://github.com/Kykaneek/RouteMail/assets/119660944/70f5d9b0-14b2-4fb9-b2b4-dc1036a91819)

https://github.com/Kykaneek/RouteMail/commit/9ca987fdc73fa9561e5a43e946a28e0bae8eed24
https://github.com/Kykaneek/RouteMail/commit/47a4ee4d4d400631dad17ade180175b148020eb9
