### ISSUE TITLE
Propozycja wstawienia wstawki kodu UI dla rozdziału 8

### ISSUE THREAD

**Issue by mkk90367** [Kykaneek/RouteMail#21]
Propozycja wstawienia wstawki kodu UI dla rozdziału 8 dokumentacji : Przykładowy kod obsługi interfejsu graficznego
Jak coś, to mogę dodać jakiś kod UI naszej apki wraz z jego opisem.

**Comment by Kykaneek** [comment]
Mracin - wstaw ekran logowania, widok 1 cruda i widok listy obsługi zleceń(z tym iż musze skończyć implementacje, wrzuć tymczasowo) - starcz

**Comment by Kykaneek** [comment]
Prośba jest taka by to napisać skrótowo co od czego jest - proszę nie rozpisuj się na temat podstaw JS czy TS. Skup się na komunikacji między poszczególnymi danymi - czyli co gdzie się zapisuje, w jaki sposób, w której tabeli i tyle.

**Comment by mkk90367** [comment]
Dopisałem już pewne treści do dokumentacji, która znacznie przez to "urosła". Zarówno merytorycznie jak i w ilości stron (35).
"Widok listy obsługi zleceń" dodam, gdy implementacja będzie gotowa.
