### ISSUE TITLE
KGDPMK-50 |  Autoryzacja Użytkowników wraz z zasalaniem i Hashowaniem

### ISSUE THREAD

**Issue by Kykaneek** [Kykaneek/RouteMail#23]
Wywalczone :)

**Comment by mkk90367** [comment]
Super :) 
Jak przetestować u siebie nowe logowanie?

**Comment by Kykaneek** [comment]
Jest ok <br>
Poniżej schemat bazy z danymi <br>

[routemail_1805.txt](https://github.com/Kykaneek/RouteMail/files/15366787/routemail_1805.txt)

Dane do logowania:<br>

email: Krystian@lubeiplacki.pl<br>
numer Kuriera: dddd<br>
Hasło: sss
